apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubestash
  namespace: argocd
spec:
  destination:
    namespace: kubestash
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/kubestash/base
    repoURL: https://github.com/appscode/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

  ignoreDifferences:
  - jsonPointers:
    - /data
    kind: Secret
    name: kubestash-kubestash-operator-webhook-cert
    namespace: kubestash
  - group: apps
    kind: Deployment
    name: kubestash-kubestash-operator-operator
    namespace: kubestash
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1apiregistration.yaml
  - group: apps
    kind: Deployment
    name: kubestash-kubestash-operator-webhook-server
    namespace: kubestash
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1apiregistration.yaml
