apiVersion: v2
appVersion: v0.0.1
description: A Helm chart for TaskQueue
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
maintainers:
- email: support@appscode.com
  name: appscode
name: taskqueue
sources:
- https://github.com/appscode-cloud
type: application
version: v2025.6.30
